config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("music/", include("musics.urls", namespace="musics")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
"""
define url that starts with /
"""
from django.urls import path
from core import views


app_name = "core"


urlpatterns = [
    path("", views.LoginView.as_view(), name="login"),
    path("login/google/", views.google_login, name="google-login"),
    path("login/google/callback/", views.google_callback, name="google-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
]

musics/urls.py
"""
define url that starts with /music
"""
from django.urls import path
from musics import views


app_name = "music"


urlpatterns = [
    path("", views.main, name="main"),
]

users/urls.py
"""
define urls that starts with /users
"""
from django.urls import path
from users import views


app_name = "users"


urlpatterns = [
    path("", views.SignupView.as_view(), name="user"),
    path("mypage/", views.Mypage.as_view(), name="mypage"),
    path("logout/", views.log_out, name="logout"),
]

templates/partials/footer.html
{% block content %}
    <footer class="flex flex-row justify-between items-center mt-auto text-gray-500 h-12 py-12 text-lg">
        <p>COPYRIGHT © 2020. Min Chul Roh, All rights reserved.</p>
        <div>
            <a href="https://peter-roh.github.io/" class="text-gray-500 no-underline"><i class="fas fa-home"></i></a>
            <a href="https://github.com/Peter-Roh" class="text-gray-500 no-underline"><i class="fab fa-github"></i></a>
        </div>
    </footer>
</body>
</html>
{% endblock content %}

templates/partials/header.html
{% load static %}
{% block content %}
    <header class="flex justify-between items-center text-xl mt-8 pb-8 h-16">
        <div class="menu-bar">
            <div class="menu-bar__menu uppercase"><a href="{% url 'musics:main' %}">home</a></div>
            <div class="menu-bar__menu uppercase">discover</div>
            <div class="menu-bar__menu uppercase">genres</div>
            <div class="menu-bar__menu uppercase">my playlist</div>
        </div>
        <div class="user__modal hidden bg-white shadow-xl" id="user__modal">
            <a class="modal__content" href="{% url 'users:mypage' %}">MY PAGE</a>
            <a class="modal__content" href="{% url 'users:logout' %}">SIGN OUT</a>
        </div>
        <i class="fas fa-bars" id="bar-icon"></i>
        <div class="user__status flex justify-end">
            <!--if logged in show avatar and username else send user to login page -->
            <div class="login-box">
                {% if user.is_authenticated %}
                    {% if user.avatar %}
                        <img src="{{user.avatar.url}}" alt="user avatar" id="user__avatar" onclick="controlModal()">
                    {% else %}
                        <img src="{% static 'images/profile_dummy.png' %}" alt="no avatar" id="user__avatar" onclick="controlModal()">
                    {% endif %}
                    <div class="user__username">{{user.username}}</div>
                {% else %}
                    <button class="login" onclick="location.href='{% url 'core:login' %}'">login</button>
                {% endif %}
            </div>
        </div>
    </header>
    <div class="mobile__bar hidden bg-gray-100" id="mobile__bar">
        <div class="mobile-bar__menu"><a href="{% url 'musics:main' %}">home</a></div>
        <div class="mobile-bar__menu">discover</div>
        <div class="mobile-bar__menu">genres</div>
        <div class="mobile-bar__menu">my playlist</div>
    </div>
    <script>
        openBar();
        const outside = document.getElementsByTagName("body")[0];
        outside.addEventListener("click", (event) => {
            if(event.srcElement.id && event.srcElement.id == "user__avatar") {
                return;
            }
            const elt = document.getElementById("user__modal");
            if(!elt.classList.contains("hidden")) {
                elt.classList.add("hidden");
            }
        });
        function controlModal() {
            const elt = document.getElementById("user__modal");
            elt.classList.toggle("hidden");
        }
    </script>
{% endblock content %}