config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("music/", include("musics.urls", namespace="musics")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
"""
define url that starts with /
"""
from django.urls import path
from core import views


app_name = "core"


urlpatterns = [
    path("", views.LoginView.as_view(), name="login"),
    path("login/google/", views.google_login, name="google-login"),
    path("login/google/callback/", views.google_callback, name="google-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
]

users/urls.py
"""
define urls that starts with /users
"""
from django.urls import path
from users import views


app_name = "users"


urlpatterns = [
    path("", views.SignupView.as_view(), name="user"),
    path("mypage/", views.Mypage.as_view(), name="mypage"),
    path("logout/", views.log_out, name="logout"),
]

users/models.py
"""
define models related to users
"""
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):

    """ Custom User Model """

    GENDER_MALE = "male"
    GENDER_FEMALE = "female"
    GENDER_OTHER = "other"

    GENDER_CHOICES = (
        (GENDER_MALE, "Male"),
        (GENDER_FEMALE, "Female"),
        (GENDER_OTHER, "Other"),
    )

    LOGIN_DEFAULT = "default"
    LOGIN_GOOGLE = "google"
    LOGIN_KAKAO = "kakao"

    LOGIN_CHOICES = (
        (LOGIN_DEFAULT, "Default"),
        (LOGIN_GOOGLE, "Google"),
        (LOGIN_KAKAO, "Kakao"),
    )

    avatar = models.ImageField(upload_to="avatar", blank=True)
    birth = models.DateField(null=True, blank=True)
    gender = models.CharField(choices=GENDER_CHOICES, max_length=7, blank=True)
    login_method = models.CharField(max_length=50, choices=LOGIN_CHOICES, default=LOGIN_DEFAULT)
    superhost = models.BooleanField(default=False)

users/forms.py
"""
define forms related to users
"""
import datetime
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm
from django.forms.widgets import PasswordInput
from users.models import User


class SignupForm(forms.Form):

    """ sign up form definition """

    this_year = datetime.datetime.today().year
    YEARS = [x for x in range(1940, this_year + 1)]

    username = forms.CharField()
    email = forms.EmailField()
    password = forms.CharField(widget=PasswordInput)
    password1 = forms.CharField(widget=PasswordInput, label="Confirm Password")
    gender = forms.ChoiceField(choices=User.GENDER_CHOICES)
    birthday = forms.DateField(
        widget=forms.SelectDateWidget(years=YEARS),
        initial=datetime.date.today
    )

    def clean_username(self):
        '''  check username '''
        username = self.cleaned_data.get("username")
        try:
            User.objects.get(username=username)
            raise forms.ValidationError("That username is already taken. ")
        except User.DoesNotExist:
            return username

    def clean_password1(self):
        ''' check password '''
        password = self.cleaned_data.get("password")
        password1 = self.cleaned_data.get("password1")
        if password != password1:
            raise forms.ValidationError("Password confirmation does not match. ")
        else:
            return password

    def save(self):
        ''' sign up user '''
        username = self.cleaned_data.get("username")
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        gender = self.cleaned_data.get("gender")
        birth = self.cleaned_data.get("birthday")
        user = User.objects.create_user(username, password)
        user.email = email
        user.gender = gender
        user.birth = birth
        user.set_password(password)
        user.save()


class CustomUserChangeForm(UserChangeForm):

    """ custom user change form """

    class Meta:
        model = get_user_model()
        fields = ("email", "avatar", "gender")

users/views.py
"""
define views related to users
"""
from django.contrib.auth import authenticate
from django.contrib.auth import login
from django.contrib.auth import logout
from django.contrib.auth.views import PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import FormView
from django.views.generic import UpdateView
from django.shortcuts import redirect
from django.shortcuts import reverse
from django.urls import reverse_lazy
from users import forms
from users.models import User
from users import mixins


class SignupView(mixins.LoggedOutOnlyView, FormView):

    """ signup view definition """

    template_name = "users/user.html"
    form_class = forms.SignupForm
    success_url = reverse_lazy("musics:main")

    def form_valid(self, form):
        form.save()
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=username, password=password)
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)

def log_out(request):

    """ sign out a user """

    logout(request)
    return redirect(reverse("core:login"))


class Mypage(SuccessMessageMixin, UpdateView):

    """ mypage to update profiles """

    template_name = "users/mypage.html"
    model = User
    success_url = reverse_lazy("musics:main")
    success_message = "Profile Updated"
    fields = ("email", "avatar", "gender")

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        return super().form_valid(form)


class UpdatePassword(SuccessMessageMixin, PasswordChangeView):

    pass

templates/users/main.html
{% extends "base.html" %}
{% block content %}
<div class="main">
    <div class="main__welcome">Upload your music!</div>
    <div class="welcome__sub">IndieRecords is a platform for indie musicians. </div>
    <div class="login__box">
        <button id="google">
            <i class="fab fa-google"></i>
            Login with Google
        </button>
        <button id="facebook">
            <i class="fab fa-facebook-f"></i>
            Login with Facebook
        </button>
        <form action="" method="POST" id="login-form">
            {% csrf_token %}
            <input type="text" placeholder="ID" name="userID" id="id">
            <input type="password" placeholder="PASSWORD" name="userPassword" id="password">
            <input type="submit" value="Sign in" id="submit">
        </form>
        <input type="button" value="Sign up!" id="signup" onclick="location.href='{% url 'users:signup' %}'">
    </div>
</div>
{% endblock content %}

templates/users/mypage.html
{% extends "base.html" %}
{% block content %}
{% include "partials/header.html" %}
<div class="mypage">
    <div class="mypage__box">
        <form action="{% url 'users:mypage' %}" method="POST" id="mypage-form" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <button class="btn" id="mypage__button">Save changes</button>
        </form>
        <!--회원 탈퇴-->
    </div>
</div>

{% include "partials/footer.html" %}
{% endblock content %}

templates/users/signup.html
{% extends "base.html" %}
{% block content %}
<div class="signup">
    <div class="signup__box">
        <p class="signup__text">Sign up!</p>
        <button class="btn" id="signup__google">
            <i class="fab fa-google"></i>
            Sign up with Google
        </button>
        <button class="btn" id="signup__facebook">
            <i class="fab fa-facebook-f"></i>
            Sign up with Facebook
        </button>
        <button class="btn" id="signup__button" onclick="location.href='{% url 'users:signup' %}'">Sign up!</button>
    </div>
</div>
{% endblock content %}

templates/users/user.html
{% extends "base.html" %}
{% block content %}
{% include "partials/header.html" %}
<div class="signup">
    <div class="signup__box">
        <form action="{% url 'users:user' %}" method="POST" id="signup-form">
            {% csrf_token %}
            {{form.as_p}}
            <button class="btn shadow-2xl" id="signup__button">Sign up!</button>
        </form>
    </div>
</div>
{% include "partials/footer.html" %}
{% endblock content %}